task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-13-0-snap
  test_script:
    - pkg install -y perl5
    - echo|cpan App::cpanminus
    - cpanm --installdeps .
    - perl Makefile.PL
    - make
    - make test

task:
  name: MacOS
  osx_instance:
    image: catalina-xcode-12.0
  test_script:
    - echo|cpan App::cpanminus
    - /Users/anka/perl5/bin/cpanm --installdeps .
    - export PERL5LIB=/Users/anka/perl5/lib/perl5
    - perl Makefile.PL
    - make
    - make test
