task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-13-0-snap
  test_script:
    - pkg install -y perl5
    - echo|cpan App::cpanminus
    - cpanm --installdeps .
    - perl Makefile.PL
    - make
    - make test

task:
  name: MacOS
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  test_script:
    - echo|cpan App::cpanminus
    - /Users/admin/perl5/bin/cpanm --installdeps .
    - export PERL5LIB=/Users/admin/perl5/lib/perl5
    - perl Makefile.PL
    - make
    - make test
